codecov:
  token: secret:8YBL5ZgBw128TiX9ZrzWtiHROjqup7hCh78wuNO6Ul1wy2ykSuMTg4apnITrepV4JXqA+c4CpdfLgoJZX6V4UUWEXOBNqSRpvoI9rPz/pzI=
  notify:
    after_n_builds: 9

coverage:
  range: 90..100

comment:
  after_n_builds: 9
